### PR TITLE
Support end to end encryption for node client

### PR DESCRIPTION
**Pull request by zymap**
After this pr is apache/pulsar#9074 merged, we can consider enabling end-to-end encryption for the node client.

Enabling end-to-end encryption
Add producer, consumer examples and test certificates

---

Because this PR needs the PR apache/pulsar#9074, I will use the latest pulsar release to release a new version of the client-node at the branch e2e.

### CODE REVIEW

**Comment by bdkanand** [comment]
Is this merged pull request published in latest pulsar-client npm module?

I do not see these changes in pulsar-client 1.3.0

**Comment by tuteng** [comment]
https://github.com/apache/pulsar-client-node/pull/138 Yes, it has been merged, but I think it will be released in 1.4.0 @bdkanand

**Comment by bdkanand** [comment]
Thanks a lot.

Do we have any ETA on when the 1.4.0 verison will be released?

Also, i see in Index.ts, the consumerConfig class do not have any property of
publickey though i see you have added that in the Consumer.cc

Can you please elaborate on that?

**Comment by tuteng** [comment]
I'm not sure when 1.4.0 will be released, but I think you could try sending an email to `dev@pulsar.apache.org` to discuss this

You don't need to configure the publicKey in consumeConfig, because the publicKey is used on the producer side to encrypt and the privateKey is used on the consumer side to decrypt, of course, you can add this configuration, but it won't be used.

**Pull request merged**
